apiVersion: v1
kind: PersistentVolume
metadata:
  name: congressus-cache
  namespace: anvt
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /data2/anvt/congressus-cache
