apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: congressus-cache
  namespace: anvt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: congressus-cache
